### PR TITLE
add support for changing the model with --model/-m

### PR DESCRIPTION
**Pull request by charlesdaniels**
Does exactly what it says on the tin. Does not support custom models yet. Here is a usage example:

```plain

$ ./chatgpt -m text-davinci-003 -q "Explain what the following shell command does: awk 'NF>1'"

This command uses the awk utility to print the lines that contain more than one field (column). This can be used, for example, to process a text file and select all lines with more than one word.
$ ./chatgpt -m text-curie-001 -q "Explain what the following shell command does: awk 'NF>1'"

This shell command uses awk to print the first line of every file in the current directory, excluding the file named NF. Because NF is a file name, the command prints nothing, which is what you would expect.
$ ./chatgpt -m text-babbage-001 -q "Explain what the following shell command does: awk 'NF>1'"

This shell command prints the string "Yes, $1" to the console.
```

### CODE REVIEW

**Comment by verdverm** [comment]
Thanks @charlesdaniels, I've been meaning to do something like this, a couple of thoughts

#### What if we check that the model is in a list?

Instead, let the API return an error, and present that to the user. We can just assume the user knows what they should put in there. This ought to support custom models too?


### Example usage

We should add a section to the long help to show an example of using a different / custom model. Adding a link to the long help string for where to find valid model names would help with the previous point.


### model command in interactive prompt

It would be nice if we could switch models in interactive mode too.

A `"model"` case just before this one https://github.com/verdverm/chatgpt/blob/main/main.go#L400 with similar logic should be all it takes

**Comment by charlesdaniels** [comment]
Yeah I was waffling on whether to explicitly check it against a list or just bubble up the API error. Considering the new GPT3.5 release I think that validates the idea we should just accept and arbitrary string as you suggest.

Adding an example to the help with a usage example is a good idea.

I didn't realize about the interactive prompt, but yeah that should be simple since the currently selected model is just a string. I imagine you could get some funky results changing models half way through an interactive session, but if the user wants to do that, I don't see any reason to stop them from doing so.

I have kept meaning to get back to you with an updated PR, but I've been busy this week. I'll make these changes as soon as I get a chance :).

**Comment by charlesdaniels** [comment]
I implemented those changes, no issues.

The GPT3 library you were using has been replaced by `go-openai` by it's own author, so I went ahead and updated to that. I did test if `gpt-3.5-turbo` would work, however unfortunately it looks like it uses the new "chat completion" system. That will need a little extra donkey work to support.

**Comment by verdverm** [comment]
Cool, looks good.

One last thing, can you replace the code block in the readme with the latest help message from the cli?

**Comment by verdverm** [comment]
and also the interactive first help message

**Comment by verdverm** [comment]
Thanks for the contribution @charlesdaniels 

I'll update the readme post merge

**Comment by charlesdaniels** [comment]
Oops yeah I meant to add those two nits but I forgot. Thanks.

**Pull request merged**
