### PR TITLE
Use the question when piping content

### PR DESCRIPTION
**Pull request by ebetica**
I think it useful to do something like pipe with a question or ask, instead of typing the question and piping the whole thing.

### CODE REVIEW

**Comment by verdverm** [comment]
I'm not sure what you mean. This change means that if a question is supplied, then you cannot pipe content from vim to the command anymore. Can you provide some examples?

The intention of the current implementation is to allow you to highlight some text or code in vim, while providing a prompt before and a question afterwards, without having to put the prompt | question text into the vim buffer.

**Comment by ebetica** [comment]
I didn't really test this thoroughly, but it should allow for `cat file.txt | chatgpt -q "Can you tell me what's in this file?"`

**Comment by verdverm** [comment]
That is how it already works today. The proposed change would break that, as the only place `stdin` is read is inside the condition where `question == ""` was added. By adding this, the code to read `stdin` will no longer be reached when `-q` is supplied.

I still don't understand what the issue is or how this solves it. Can you provide a complete example for what is not possible?

**Comment by ebetica** [comment]
Okay, I just tested it, without my patch:

```
$ git show HEAD | chatgpt -q "Can you provide a detailed summary of this commit?" 

This commit adds a new feature to the project by creating a new page in the admin panel. It adds a new endpoint to the application to support the new page, as well as a new service to handle the business logic for the endpoint. It also adds a new controller for the endpoint, and updates the routing file to map the new endpoint. Finally, it adds some unit tests for the new endpoint and service.
```


With the patch:
```
$ git show HEAD | ./chatgpt -q "Can you provide a detailed summary of this commit?"

This commit updates the main.go file in the project by changing a section of code to no longer use the question when piping content. This change ensures that the program reads from stdin when no args are provided or when interactive mode is enabled.
```

the commit in question is the commit in this PR. Without the PR, it ignores anything you pipe to it when you provide a question, and with the commit it will actually read things piped to it in addition to reading the question.

**Comment by verdverm** [comment]
🤦‍♂️ I've been reading the red|green backwards, you are correct, sorry about that

**Comment by verdverm** [comment]
Thanks for the improvement @ebetica

**Pull request merged**
